services:

  frontend:

    build: ./frontend
    ports:
      - "80:80"
    networks:
      - idade-network
    depends_on:
      - backend # Garante que o Nginx inicie depois que o back esteja disponível, apenas para seguir uma ordem

  backend:

    build: ./backend
    environment:
      DB_HOST: db
      DB_USER: user
      DB_NAME: db-idade-app-py
    secrets:
      - mysql_root_password
      - mysql_password
    ports:
      - "5000:5000"
    networks:
      - idade-network
    depends_on:
      - db

  db:

    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
    secrets:
      - mysql_root_password
      - mysql_password
    ports:
      - "3306:3306"
    volumes:
      - db-data-idade:/var/lib/mysql
    networks:
      - idade-network
  
volumes:
  db-data-idade:

networks:
  idade-network:
    driver: bridge

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt

  mysql_password:
    file: ./secrets/mysql_password.txt