
services:

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - idade-network
    depends_on:
      - backend


  backend:
    build: ./backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "5000:5000"
    networks:
      - idade-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db-data-idade:/var/lib/mysql
    networks:
      - idade-network



volumes:
  db-data-idade:

networks:
  idade-network:
    driver: bridge
