version: "3.8"

services:

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - idade-network
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_USER: user
      DB_NAME: db_idade_app_py
      DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "5000:5000"
    networks:
      - idade-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: db_idade_app_py
      MYSQL_USER: user
    ports:
      - "3306:3306"
    volumes:
      - db-data-idade:/var/lib/mysql
    networks:
      - idade-network

volumes:
  db-data-idade:

networks:
  idade-network:
    driver: bridge
